name: frontend
description: Plateforme numérique dédiée aux enseignements de Serigne Sam Mbaye.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  go_router: ^14.0.0
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  just_audio: ^0.9.0
  video_player: ^2.9.0
  chewie: ^1.8.0
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
