# Generated by Django 5.2.15 on 2026-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier', models.FileField(upload_to='videos/')),
                ('image_miniature', models.ImageField(blank=True, null=True, upload_to='miniatures/videos/')),
                ('duree', models.DurationField(blank=True, null=True)),
                ('date_publication', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
                'ordering': ['-date_publication'],
            },
        ),
    ]
