# Generated by Django 5.2.15 on 2026-06-19 17:08

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='fichier',
            field=models.FileField(storage=config.storage.video_storage, upload_to='videos/'),
        ),
    ]
