# Generated by Django 5.2.15 on 2026-06-19 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('videos', '0002_alter_video_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='albums.album'),
        ),
    ]
