# Generated by Django 5.2.15 on 2026-06-19 23:01

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='lien_externe',
            field=models.URLField(blank=True, help_text="URL directe d'une vidéo hébergée ailleurs (ex. Internet Archive .mp4). Prioritaire sur le fichier si renseigné.", max_length=500),
        ),
        migrations.AlterField(
            model_name='video',
            name='fichier',
            field=models.FileField(blank=True, storage=config.storage.video_storage, upload_to='videos/'),
        ),
    ]
