// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVKQuyGe1-UM537aDuTiqqTwr18RIO1yY',
    appId: '1:443768597916:web:0c3961041def3a3ac8ac59',
    messagingSenderId: '443768597916',
    projectId: 'serigne-sam-mbaye-app',
    authDomain: 'serigne-sam-mbaye-app.firebaseapp.com',
    storageBucket: 'serigne-sam-mbaye-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtqGkYBqNg61NRmYGEEcHaYuscalddWms',
    appId: '1:443768597916:android:bf8e25e5f721e0edc8ac59',
    messagingSenderId: '443768597916',
    projectId: 'serigne-sam-mbaye-app',
    storageBucket: 'serigne-sam-mbaye-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ALamRDcm9pSQEBzbNyVzieiw3SDf0cM',
    appId: '1:443768597916:ios:18cf12364dd91c86c8ac59',
    messagingSenderId: '443768597916',
    projectId: 'serigne-sam-mbaye-app',
    storageBucket: 'serigne-sam-mbaye-app.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ALamRDcm9pSQEBzbNyVzieiw3SDf0cM',
    appId: '1:443768597916:ios:18cf12364dd91c86c8ac59',
    messagingSenderId: '443768597916',
    projectId: 'serigne-sam-mbaye-app',
    storageBucket: 'serigne-sam-mbaye-app.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVKQuyGe1-UM537aDuTiqqTwr18RIO1yY',
    appId: '1:443768597916:web:c164024a3cec2f6cc8ac59',
    messagingSenderId: '443768597916',
    projectId: 'serigne-sam-mbaye-app',
    authDomain: 'serigne-sam-mbaye-app.firebaseapp.com',
    storageBucket: 'serigne-sam-mbaye-app.firebasestorage.app',
  );
}
