# Generated by Django 5.2.15 on 2026-06-19 22:08

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_audio_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='fichier',
            field=models.FileField(storage=config.storage.audio_storage, upload_to='audios/'),
        ),
    ]
