# Generated by Django 5.2.15 on 2026-06-19 23:01

import config.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_alter_audio_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='lien_externe',
            field=models.URLField(blank=True, help_text="URL directe d'un audio hébergé ailleurs (ex. Internet Archive .mp3). Prioritaire sur le fichier si renseigné.", max_length=500),
        ),
        migrations.AlterField(
            model_name='audio',
            name='fichier',
            field=models.FileField(blank=True, storage=config.storage.audio_storage, upload_to='audios/'),
        ),
    ]
